server:
  port: 8082
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/msvc-hotel
        username: postgres
        password: 2357
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
