server:
  port: 0

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc-hotel
    username: postgres
    password: 2357
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # Configura el ID de instancia para que sea único y reconocible
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
